#test against this version of Node:
environment:
   matrix:
      - nodejs_version: "6"

#install scripts (runs after cloning)
install:
   #get the latest stable node.js or io.js
   - ps: Install-Product node $env:nodejs_version
   #install modules
   - npm install

#post install test
test_script:
   #output useful debugging data
   - node --version
   - npm --version
   # run tests
   - npm test

#don't actually bulid
build: off
